[package]
name = "segmented_button"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
iced_aw = { workspace = true, features = [
    "segmented_button",
    "icons",
] }
iced.workspace = true