[package]
name = "drop_down"
version = "0.1.0"
authors = ["wiiznokes <wiiznokes2@gmail.com>"]
edition = "2021"


[dependencies]
iced_aw = { workspace = true, features = [
    "drop_down",
    "icons",
] }
iced.workspace=true
