[package]
name = "context_menu"
version = "0.1.0"
authors = ["wiiznokes <wiiznokes2@gmail.com>"]
edition = "2021"


[dependencies]
iced_aw = { workspace = true, features = [
    "context_menu",
    "icons",
] }
iced.workspace = true
