[package]
name = "font_loading"
version = "0.1.0"
authors = ["Redhawk18"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced.workspace=true
iced_aw = { workspace = true, features = [ "icons" ] }

